name: implicit_navigator
description: An easy and intuitive navigator that updates the page stack in response to app state changes and the system back button.
repository: https://github.com/caseycrogers/implicit_navigator

version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true