name: implicit_navigator
description: Intuitive and highly flexible navigation with an easy to use API.
repository: https://github.com/caseycrogers/ImplicitNavigator

version: 0.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true