name: implicit_navigator
description: An intuitive and highly flexible navigation system with an easy to use API.
repository: https://github.com/caseycrogers/implicit_navigator

version: 0.0.5

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true